name: PR health check

on:
  pull_request:
    branches:
        - main

jobs:
  trigger-remote:
    runs-on: ubuntu-latest

    steps:


        - name: set pr health check to pending status
          run: |
            curl -X POST -H "Authorization: token ${{secrets.TEST_TOKEN_JOY}}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 -H "Content-Type: application/json" \
                 https://api.github.com/repos/${{github.repository}}/statuses/${{github.event.pull_request.head.sha}} \
                 -d '{"state": "pending", "context": "pr health check", "description": "waiting for remote workflow"}'

        - name: Trigger remote workflow
          run: |
            curl -X POST -H "Authorization: token ${{secrets.TEST_TOKEN_JOY}}" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Content-Type: application/json" \
              https://api.github.com/repos/sangeet-joy-tw/workflow-refactor-test-repo/actions/workflows/pr.yml/dispatches \
              -d '{
                "ref": "main",
                "inputs": {
                  "pr_number": "${{ github.event.pull_request.number}}",
                  "callback_url": "https://api.github.com/repos/${{github.repository}}/dispatches",
                  "pr_sha": "${{github.event.pull_request.head.sha}}"
                  }
                }'